project:
  type: website
  output-dir: _docs


website:
  page-navigation: true
  title: "AM 1 <br> Populismusforschung"
  description: "Homepage "

  repo-url: https://github.com/jasminskoenig/AM1-populism.git
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@jasminskoenig"
    image: "images/twitter-card.png"

  sidebar:
    background: "#CEB7BB" # Thistle
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/jasminskoenig/AM1-populism.git
        text: "GitHub Website"
      - icon: person-fill
        href: https://www.jasminskoenig.com
        text: "Jasmin Homepage"
      - icon: camera-video-fill
        href: https://uni-hamburg.zoom.us/j/65339868930?pwd=TWNFZm9TcFN5cHdTZDhweTZuQWFXdz09
        text: "Zoom"
 
    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Kursinformationen"
        contents:
          - href: course-overview.qmd
            text: Allgemeines
          - href: index.qmd
            text: Syllabus
          - href: lektuere.qmd
            text: Lektuere
          - href: course-links.qmd
            text: Hilfreiche Links
          - href: course-faq.qmd
            text: FAQ
          - href: sprechstunde.qmd
            text: Sprechstunde
      - section: "Credits"
        contents:
          - href: studienleistung.qmd
            text: Studienleistung
          - href: hausarbeit.qmd
            text: Hausarbeit

  page-footer:
    right: "This page is built with a template by <a href='https://mine-cr.com/'>Mine Çetinkaya-Rundel</a> with 💛 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Jasmin Sarah König"
    background: "#CEB7BB" # Rose Quartz

format:
  html:
    theme:
      light: [cosmo, style/am1.scss]
      dark: [cosmo, style/am1.scss, style/dark.scss]
    linkcolor: "#689295" # Blue (Munsell)
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto

editor: visual
