---
title: "AM1: Vergleichende Empirische Populismusforschung"
subtitle: "Jasmin Sarah König"
execute:
  freeze: false
editor_options: 
  chunk_output_type: console
---

Auf dieser Seite findet ihr den Kursplan für das Semester. Alle Lektüren, Fragenkataloge und die Slides der Präsentationen sind hier verlinkt.

Bitte nehmt in der Syllabus das **verpflichtende Blockseminar** am 30. Juni zur Kenntnis!

```{r}
#| echo: false
#| message: false
#| warning: false

library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/1Zq8Fhhlln_1RBXzqshvEdoFXcmt3LldwmTnxanbLEjI/edit?usp=sharing")
```

<div>

```{r}
#| echo: false

d |>
  mutate(
    Datum = as.Date(Datum)
  ) |>
  select(-Notes, -Lecturenotes) |> 
  gt() |>
  fmt_date(Datum, date_style = 31) |>
  sub_missing(columns = c(Woche, Uhrzeit, Thema, Lektüre, Raum, Fragen), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(Woche)
    ) |>
  cols_align(
    align = "right", 
    columns = c(Datum, Raum)
    ) |>
  cols_align(
    align = "left", 
    columns = c(Thema, Lektüre, Fragen)
    ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(Raum, Datum, Thema, Lektüre)
    )
  ) |>
  fmt_markdown(
    columns = c(Raum, Thema, Lektüre)
  ) |>
  cols_width(
    Woche ~ px(40),
    Datum ~ px(100),
    Uhrzeit ~ px(180),
    Raum ~ px(130),
    Thema ~ px(500),
    Lektüre ~ px(500)) # only needed for a column that is nto supposed to have a title on website#|>
  # cols_label(
  #   what = ""
  # )
```

</div>
