---
title: "Unterstützung"
---

## Sprechstunde

Meldet euch gerne für einen Sprechstundentermin bei mir per [E-mail](mailto:jasmin.sarah.koenig\@uni-hamburg.de). Grundsätzlich habe ich Dienstags zwischen 14 und 16 Uhr immer für in-person Sprechstunden Termine Zeit, wir können aber gerne auch nach einem anderen Zeitfenster schauen. 

Ort: VMP9 A 408 oder [Zoom](https://uni-hamburg.zoom.us/j/65339868930?pwd=TWNFZm9TcFN5cHdTZDhweTZuQWFXdz09)

## Email

Ihr erreicht mich [hier](mailto:jasmin.sarah.koenig\@uni-hamburg.de) via E-mail.

### Technik

Solltet ihr technische Probleme haben (ein wichtiger Websitelink funktioniert nicht oder der wöchentliche Fragenkalatog funktioniert nicht), meldet euch bitte schnellstmöglich via E-mail bei mir. Wahrscheinlich haben in dem Fall andere ein ähnliches Problem, da ein Fehler im Code vorliegt. Das behebe ich nach eurer Meldung so schnell wie möglich.

### Sonstiges

Auch mit anderen Fragen könnt ihr euch gerne jederzeit via Mail an mich wenden. Von Montag-Freitag versuche ich euch an demselben Tag noch zu antworten. Am Wochenende werden die E-mails allerdings nicht gelesen.
