---
title: "Studienleistung"
---

Um für den Kurs die Credits angerechnet zu bekommen, muss eine Studienleistung abgelegt werden. Das Seminar verzichtet auf wöchentliche Referate, dafür werden 3 kleine Studienleistungen erwartet.

## Wöchentliche Fragen

Jede Woche sind einige Fragen zur Lektüre zu beantworten. Diese sind immer ab Dienstag in der \[Syllabus\](/index.qmd). Die Fragen sind bis zum **Montag** vor dem Seminar um **12 Uhr mittags** zu beantworten. Orientiert euch an einem Maximum von 5 Sätzen. Wenn die Frage für euch in weniger Worten zu beantworten ist, macht das gerne!

Die Fragen dürfen pro Person in jeweils zwei Wochen verpasst werden.

### Lesefragen

Für jede Sitzung muss vorab ein Paper/Kapitel gelesen werden. Um die Lektüre etwas einfacher zu gestalten, werden jede Woche Fragen zu der Lektüre hoch geladen. Ich werde die Fragen am Montag noch zur Vorbereitung des Seminars am Dienstag nutzen, und den Kurs so vorzubereiten, dass alle Fragen zum Text im Laufe des Seminars diskutiert werden können.

### Social Media Analyse

Über das Semester folgt jede:r Teilnehmende einem Politiker auf einem Social Media Kanal. Bitte achtet insbesondere bei rechtsaußen Politiker:innen - falls möglich - darauf, den Kanal nicht zu liken, sondern ihn nur zu abbonieren. In dem wöchentlichen Fragenkatalog befindet sich jede Woche auch eine Frage zu dem Social Media Kanal, dem gefolgt wird. In einigen Fällen bezieht dieser sich auf die Lektüre (beispielsweise "Welches Konzept des Begriffs"Volk" nutzt der:die Politiker:in auf ihrem:seinem Kanal?", in manchen Wochen frage ich nur nach einer kurzen Zusammenfassung). Auch hier gilt, zwei bis drei Sätze reichen vollkommen. Es geht bei der Aufgabe darum, die Anwendung von Konzepten auf die Empirie regelmäßig zu üben.

## Blockseminar

Wir werden das Blockseminar nutzen um zu üben selber Forschungsideen zu konzeptualisieren. Die aktive Teilnahme daran ist Teil der Studienleistung. Ob am Ende des Blockseminars eine kleine Zusammenfassung abzugeben ist, gebe ich rechtzeitig bekannt.

## Anwesenheitspflicht

Für den Kurs gilt eine Anwesenheitspflicht. Zwei Seminare dürfen ohne Grund verpasst werden (eine kurze Notiz vorab freut mich aber). Solltet ihr darüber hinaus länger verhindert sein (beispielsweise durch eine Krankheit), kontaktiert mich bitte.

Da das **Blockseminar** drei Seminare ersetzt gilt hier Anwesenheitspflicht.
